### ISSUE TITLE
Unable to import module 'handler': cannot import name '_imaging'

### ISSUE THREAD

**Issue by YuK1Game** [bweigel/aws-lambda-tesseract-layer#4]
I ran example.
Response is `Internal server error`.
The error is the title.

**Comment by secretshardul** [comment]
> I ran example.
> Response is `Internal server error`.
> The error is the title.
#### Issues I faced earlier
```
/var/task/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned  
Unable to import module 'handler': cannot import name '_imaging'
```
# fix
AWS lambda uses IAM linux. Issue happens when different OS is used to build and deploy python file with serverless. After facing the issue I was able to fix it.
1. **simple solution**: Use [AWS cloud9](https://aws.amazon.com/cloud9/) to deploy example folder. Layer can be deployed from anywhere.
2. [**complex solution**](https://forums.aws.amazon.com/thread.jspa?messageID=915630): Deploy EC2 instance with AMI linux and get correct binaries.    

This is not limited to Pillow but is a general issue with lambdas. Also I hope you know that layer and python example are to be deployed separately.
