### ISSUE TITLE
Question about Dockerfile in al2-serverless example

### ISSUE THREAD

**Issue by alanwilter** [bweigel/aws-lambda-tesseract-layer#79]
I got https://github.com/bweigel/aws-lambda-tesseract-layer/tree/master/example/al2-serverless example to work.

What's the use of the `Dockerfile`?: https://github.com/bweigel/aws-lambda-tesseract-layer/blob/master/example/al2-serverless/Dockerfile

Do I need it? How and why? What can I practically do with it? Or I shouldn't touch it?

I used to use Docker to handle my lambdas but I was having lots of issues to create a Docker image with tesseract and your layer is a bless!

In principle I could simply change your example `handler.py` to my application needs (very similar actually to the example, except that I need to fetch images from a S3 bucket and save the output there as well), so I don't see I could need this `Dockerfile`.

So, in the end I just want to now about that `Dockerfile`. I removed and it apparently worked.

**Comment by alanwilter** [comment]
Ok, after reading in details https://www.serverless.com/plugins/serverless-python-requirements I see why `Dockerfile` may be there. But I'm not sure yet if it's critical, since it calls `FROM lambci/lambda:build-python3.8`.

**Comment by bweigel** [comment]
In general it is advisable to _keep your build and deployment-environment as similar as possible_ (to minimize problems in production). Hence, I always use docker to install python dependencies. Some dependencies (like pillow) have binary dependencies to the host OS that might break otherwise. Problems like #4 could occur.

If your usecase works without the need for dockerizing, that's totally fine.

---------

Now some technical details on how the `Dockerfile` is integrated. It is hidden in the `serverless.yml`, where I am using the [`serverless-python-requirements` plugin](https://github.com/serverless/serverless-python-requirements) ... 

https://github.com/bweigel/aws-lambda-tesseract-layer/blob/dbd7bf5abc5bf5690085744271f377f9602d0974/example/al2-serverless/serverless.yml#L4-L5

... to install additional dependencies specified in the [`requirements.txt`](https://github.com/bweigel/aws-lambda-tesseract-layer/blob/dbd7bf5abc5bf5690085744271f377f9602d0974/example/al2-serverless/requirements.txt):

https://github.com/bweigel/aws-lambda-tesseract-layer/blob/dbd7bf5abc5bf5690085744271f377f9602d0974/example/al2-serverless/serverless.yml#L11-L14

I believe I did this specifically for the [pillow](https://pillow.readthedocs.io/en/stable/) dependency. It needs binary dependencies that need to match the lambda runtime you want to run in. 

>Think about the binaries as electrical sockets/outlets. The european sockets are different from the US sockets. If you build a machine in Europe using european outlets the machine won't connect in the US.  

If everything you want to do works without the need of dockerizing, by all means do it. It will make deployments much quicker most of the time. But keep in mind binary dependencies. If you have them, dockerize.

@alanwilter I am closing the issue, but feel free to reopen if you still have questions.

**Comment by alanwilter** [comment]
Thanks @bweigel for the explanation and details.

In the end, because our app needed `tesseract` rather than `pytesseract` (so a layer wouldn't work here) I used https://github.com/bweigel/aws-lambda-tesseract-layer/blob/master/Dockerfile.al2 as an inspiration to build my complete solution.

**Comment by bweigel** [comment]
Interesting, I am not quite sure I understand, because afaik `pytesseract` just calls the `tesseract` binary included in the layer (inside the `bin` folder).

But sure enough, it should work equally well if you don't use a layer and just include everything as a dependency.

I am glad you got it figured out.

**Comment by alanwilter** [comment]
I use a library https://pypi.org/project/hvf-extraction-script/ that uses tesserocr, which:

> tesserocr integrates directly with Tesseract's C++ API using Cython which allows for a simple Pythonic and easy-to-read source code. It enables real concurrent execution when used with Python's threading module by releasing the GIL while processing an image in tesseract.

So your layer exposes just the binaries. If `hvf-extraction-script` was using `pytesseract`, then your layer would work out of the box.

In the end, I took you `Dockerfile`, changed accordingly and integrate `hvf-extraction-script` and got my lambda working.
